#!/bin/bash
[ $(id -u) -eq 0 ] || exec sudo --non-interactive --preserve-env "PATH=${PATH}" "${0}" "${@}"

set -euo pipefail
. /.functions
export LOCK="$(readlink -f "${0}")"

# Just for safety's sake
cd /

split_hostnames()
{
	if [ ${#} -gt 0 ] ; then
		echo "${@}" | split_hostnames
	else
		tr -c '[a-zA-Z0-9-]' '\n' | sed -e '/^\s*$/d'
	fi
	return 0
}

list_hostname_variations()
{
	local VARIATION="${1}"
	shift

	echo "${VARIATION}"
	get_service_ip "${VARIATION}"

	for n in "${@}" ; do
		# We stop as soon as we find an empty element
		[ -n "${n}" ] || break

		VARIATION+=".${n}"
		echo "${VARIATION}"
	done
}

get_service_ip()
{
	# Sanitize the name - convert all invalid chars to "_"
	local SERVICE_NAME="$(echo -n "${1^^}" | tr -c '[A-Z0-9]' '_')"
	local SVC_VAR="${SERVICE_NAME^^}_SERVICE_HOST"
	[ -v "${SVC_VAR}" ] || return 0
	local SVC_IP=""
	SVC_IP="$(validate_ip "${!SVC_VAR}")" || return 0
	[ "${SVC_IP}" != "127.0.0.1" ] && echo "${SVC_IP}"
	return 0
}

marker_exists()
{
	local MARKER="${1}"
	is_file "${MARKER}" || return 1
	[ -s "${MARKER}" ] || return 1
	return 0
}

wait_for_marker()
{
	local MARKER="${1}"
	local TIMEOUT=""
	TIMEOUT="$(timestr_to_secs "${2}")" || fail "Invalid timeout specification [${2}]"

	local TIMEOUT_STR="$(secs_to_timestr "${TIMEOUT}")"

	local FIRST="true"
	local START="$(date +%s)"
	while ! marker_exists "${MARKER}" ; do
		"${FIRST}" && waiting "Waiting for the ACME certificates to be initialized (up to ${TIMEOUT_STR} total)..."
		FIRST="false"

		# Poke every 100ms (10 times per second)
		sleep 0.1 || fail "Sleep interrupted"
		local NOW="$(date +%s)"

		# If the timeout has expired, return a non-zero value
		[ $(( NOW - START )) -lt ${TIMEOUT} ] || return 1
	done
	ok "ACME client is initialized is ready"
	return 0
}

is_valid_url()
{
	local URL="${1}"
	[[ "${URL}" =~ ^([^:/?#]+)://([^/?#]*)?([^?#]*)([?]([^#]*))?(#(.*))?$ ]] || return 1
	return 0
}

validate_ip()
{
	[ ${#} -ge 1 ] || return 1
	local PARTS=()
	for IP in "${@}" ; do
		is_valid_ipv4 "${IP}" || return 1
		echo "${IP}"
	done
	return 0
}

validate_cert()
{
	local CERT="${1}"
	is_file_readable "${CERT}" || return 1
	[ -s "${CERT}" ] || return 1
	openssl x509 -noout -text -in "${CERT}" &>/dev/null || return ${?}
	return 0
}

is_ca()
{
	local CERT="${1}"
	validate_cert "${CERT}" || return ${?}
	# Is the certificate a CA certificate of some kind?
	openssl x509 -noout -ext basicConstraints -in "${CERT}" | \
		tail -n +2 | \
		sed -e 's;, ;\n;g' -e 's;^\s*;;g' | \
		grep -qi "^CA:TRUE" || return ${?}
	return 0
}

install_chain()
{
	local CERT_BASE_NAME="${1}"
	local SUFFIX="${2}"
	local DEST="$(readlink -f "$(mktemp -d)")"
	local EXT="${SUFFIX:+.}${SUFFIX}"
	( cd "${DEST}" && csplit /dev/stdin '/BEGIN CERTIFICATE/' '{*}' &>/dev/null ) || return $?
	while read n ; do
		# Leave only the certificate bits in each split out file
		sed -i -e '/^-\+END CERTIFICATE-\+$/q' "${n}"

		# Keep only the files that contain certificate bits
		if grep -q "END CERTIFICATE" "${n}" && is_ca "${n}" ; then
			local SUBJECT="$(openssl x509 -noout -subject -in "${n}" | sed -e 's;^subject=;;g')"
			local ISSUER="$(openssl x509 -noout -issuer -in "${n}" | sed -e 's;^issuer=;;g')"
			say "\tInstalling certificate: ${SUBJECT}"
			[ "${SUBJECT}" != "${ISSUER}" ] && say "\tIssued by: ${ISSUER}"
			local TGT_NAME="${CERT_BASE_NAME}.${n##*/}${EXT}"
			mv -f "${n}" "${TGT_NAME}"
		else
			rm -f "${n}" &>/dev/null
		fi
	done < <(find "${DEST}" -mindepth 1 -maxdepth 1 -type f -name 'xx*')
	rm -rf "${DEST}"
}

download_from_port()
{
	local HOST="${1}"
	local SNI="${2}"
	local PORT="${3}"
	local PROTOCOL="${4}"
	local TARGET="${5}"
	local SUFFIX="${6}"

	local SNI_FLAGS=()
	[ -n "${SNI}" ] && SNI_FLAGS+=(-servername "${SNI}")

	local TLS_FLAGS=()
	if [ -n "${PROTOCOL}" ] ; then
		TLS_FLAGS+=(-starttls "${PROTOCOL}")
		[ -n "${SNI}" ]  && TLS_FLAGS+=(-name "${SNI}")
		PROTOCOL=":${PROTOCOL}"
	fi

	local CERT_BASE_NAME="${SNI}"
	[ -n "${CERT_BASE_NAME}" ] && CERT_BASE_NAME+="@"
	CERT_BASE_NAME+="${HOST}:${PORT}${PROTOCOL}"

	openssl s_client -connect "${HOST}:${PORT}" \
		"${SNI_FLAGS[@]}" "${TLS_FLAGS[@]}" \
		-showcerts </dev/null 2>/dev/null | \
			install_chain "${TARGET}/${CERT_BASE_NAME}" "${SUFFIX}"
	return 0
}

download_chain()
{
	local CERT_BASE_NAME="${1}"
	local URL="${2}"
	local SUFFIX="${3}"
	local RC=0
	OUT="$(curl -kL --fail --silent --show-error --connect-timeout 5 -o >(install_chain "${CERT_BASE_NAME}" "${SUFFIX}") "${URL}" 2>&1)" || RC=${?}
	[ ${RC} -ne 0 ] && err "Failed to download the certificates from [${URL}] (rc=${RC}):\n${OUT}"
	return ${RC}
}

split_signed_cert()
{
	local SRC="${1}"
	local CERT="${2}"
	local CHAIN="${3:-}"
	local ROOT="${4:-}"
	local INT="${5:-}"

	local OUT=""
	doing "Extracting the certificate from the signed bundle..."
	if [ $(grep -c -- "-----END CERTIFICATE-----" "${SRC}") -le 1 ] ; then
		#
		# No bundle ... just the certificate!
		#
		OUT="$(cp -vf "${SRC}" "${CERT}" 2>&1)" || fail "Failed to deploy the downloaded certificate (rc=${?}): ${OUT}"

		if [ -n "${CHAIN}" ] && [ -n "${ROOT}" ] ; then
			cat "${SSL_DIR}/ca-root.pem" > "${SSL_DIR}/ca-chain.pem" || fail "Failed to generate the certificate signing chain (rc=${?})"
			say "\t✅ Chain ready!"
		fi
		say "\t✅ Certificate ready!"
		return 0
	fi

	#
	# Signed bundle! Split it!
	#
	doing "Splitting the signed bundle..."
	if [ -n "${INT}" ] ; then
		sed -e '0,/-----END CERTIFICATE-----/d' < "${SRC}" > "${INT}" || fail "Failed to extract the intermediate CAs from the signed bundle (rc=${?})"
		say "\t✅ Intermediates ready!"
	fi

	if [ -n "${CHAIN}" ] && [ -n "${ROOT}${INT}" ] ; then
		(
			[ -n "${INT}" ] && cat "${INT}"
			[ -n "${ROOT}" ] && cat "${ROOT}"
		) > "${CHAIN}" || fail "Failed to generate the certificate signing chain (rc=${?})"
		say "\t✅ Chain ready!"
	fi

	sed -e '/-----END CERTIFICATE-----/q' < "${SRC}" > "${CERT}" || fail "Failed to extract the certificate from the signed bundle (rc=${?})"
	say "\t✅ Certificate ready!"
	return 0
}

expand_vars()
{
	echo -n "${@}" | envsubst
}

set_or_default POD_HOSTNAME "$(hostname -f)"
set_or_default SSL_DIR "/.ssl"
set_or_default SSL_ENV_FILE "${SSL_DIR}/.env"
set_or_default SSL_TRUSTS_DIR "/.trusts"

{
	flock -x 999 || fail "Failed to acquire the execution lock for SSL initialization"

	mkdir -p "${SSL_DIR}" &>/dev/null

	################################################################################
	#
	# If we've already computed all our stuff, and saved it to the SSL_ENV_FILE,
	# we need not compute it again because it can be re-used from there
	#
	################################################################################
	is_file_readable "${SSL_ENV_FILE}" && quit "SSL is already initialized, you can load the settings from [${SSL_ENV_FILE}]"

	#
	# Make sure the environment file is created every time if we exit cleanly
	#
	export RESULT_OK="false"
	finalize()
	{
		[ -v GARBAGE ] && shred -u "${GARBAGE[@]}" &>/dev/null

		# Shortcut - die early!
		as_boolean "${RESULT_OK}" || return 0

		# Output the environment file
		local DIR="$(dirname "${SSL_ENV_FILE}")"
		mkdir -p "${DIR}" &>/dev/null

		# Output the variable values!
		local UNDEF=()
		{
			echo "#!/bin/bash"
			echo ""
			echo "#"
			echo "# Source this file to define all SSL-related environment variables"
			echo "#"
			echo ""
			for VAR in "${SSL_ENV_FILE_VARS[@]}" ; do
				if [ -v "${VAR}" ] ; then
					echo "export ${VAR}=${!VAR@Q}"
				else
					UNDEF+=( "${VAR}" )
					echo "# ${VAR} was undefined"
				fi
			done
			echo ""
			echo "#"
			echo "# End of the SSL environment variable definitions"
			echo "#"
		} > "${SSL_ENV_FILE}"

		[ ${#UNDEF[@]} -gt 0 ] && \
			warn "The following variables were undefined [ ${UNDEF[@]} ]"

		# Make sure everything is readable
		chown --reference="${SECURE_FILES[0]}" "${SSL_ENV_FILE}"
		chmod --reference="${SECURE_FILES[0]}" "${SSL_ENV_FILE}"
	}
	trap finalize EXIT

	#
	# Oh? Work to be done? Let's do some initial validations first ...
	#
	set_or_default ACM_GROUP
	[ -n "${ACM_GROUP}" ] || fail "The ACM_GROUP environment variable is REQUIRED"
	getent group "${ACM_GROUP}" &>/dev/null || fail "The group [${ACM_GROUP}] does not exist"

	SSL_DIRECTORIES="$(find-ssl-dirs)" || fail "Failed to compute the local SSL configuration"
	source <(echo -n "${SSL_DIRECTORIES}") || fail "Failed to apply the local SSL configuration"

	#
	# Find the Java keytool, if it's installed
	#
	type -P keytool &>/dev/null && KEYTOOL="true" || KEYTOOL="false"

	################################################################################
	#
	# Define the FIPS flag for convenience
	#
	################################################################################
	is_fips && FIPS="true" || FIPS="false"
	export FIPS

	#
	# Configure any GoLang stuff
	#
	set_godebug_fips140

	#
	# These are the values we have to output into the environment
	# file at the end of processing
	#
	SSL_ENV_FILE_VARS=(
		SSL_DIR
		SSL_TRUSTS_DIR
		SSL_ENV_FILE

		FIPS
		GODEBUG
	)

	################################################################################
	#
	# Ok ... start doing the work!
	#
	################################################################################
	set_or_default ACME_WAIT "false"
	if as_boolean "${ACME_WAIT}" ; then
		set_or_default ACME_WAIT_TIMEOUT "20m"
		wait_for_marker "${SSL_ENV_FILE}" "${ACME_WAIT_TIMEOUT}" || fail "ACME client initialization timed out"
		quit "ACME rendering is complete, you can load the necessary variables from [${SSL_ENV_FILE}]"
	fi

	set_or_default ACME_URL "https://acme:9000"
	# Validate the URL
	[[ "${ACME_URL}" =~ ^http(s)?://([^:/]+)(:([1-9][0-9]*))?(/.*)?$ ]] || fail "Malformed URL for the ACME CA: [${ACME_URL}]"

	ACME_HOST="${BASH_REMATCH[2]}"
	ACME_PORT="80"
	[ -z "${BASH_REMATCH[1]}" ] || ACME_PORT="443"
	[ -z "${BASH_REMATCH[4]}" ] || ACME_PORT="${BASH_REMATCH[4]}"

	# Validate the values captured above ... must have a valid host and port
	is_valid_hostname "${ACME_HOST}" || fail "Malformed URL for the ACME CA: bad hostname [${ACME_URL}]"
	is_valid_port "${ACME_PORT}" || fail "The port in the URL must be between 1 and 65535"

	ACME_ROOT_CA_BASENAME="ca-root"
	ACME_ROOT_CA_ANCHOR="${OS_SSL_ANCHORS}/${ACME_ROOT_CA_BASENAME}.${OS_SSL_SUFFIX}"

	#
	# Ok ... start working our magic!
	#

	################################################################################
	#
	# Download the root CA we'll use to trust everything from this cluster
	#
	################################################################################

	# Wait up to 5 minutes for the CA to come up
	MAX_WAIT=300
	START="$(date +%s)"
	doing "Fetching the root CA certificate from [${ACME_HOST}]"
	while true ; do
		# TODO: What's the standard way to do this in ACME-land?
		OUT="$(curl -k -fsSL -o "${ACME_ROOT_CA_ANCHOR}" "${ACME_URL}/roots.pem" 2>&1)" && break
		err "Failed to get the step root CA (rc=${?}):\n${OUT}"
		NOW="$(date +%s)"
		[ $(( NOW - START )) -ge ${MAX_WAIT} ] && fail "Timed out trying to reach the CA issuer at [${ACME_URL}]"
		sleep 5 || fail "Sleep interrupted trying to wait for [${ACME_URL}] - cannot continue"
	done
	say "\t✅ Fetch OK!"

	################################################################################
	#
	# Initialize the ACME client
	#
	################################################################################
	if step ca health &>/dev/null ; then
		ok "Step CA client already initialized!"
	else
		doing "Initializing the Step CA Acme Client"
		step ca bootstrap -f \
			--ca-url "${ACME_URL}" \
			--fingerprint "$(step certificate fingerprint "${ACME_ROOT_CA_ANCHOR}")"
		say "\t✅ Done!"
	fi

	########################################
	# Copy the CA's certs into the SSL_DIR
	########################################
	doing "Copying the root CA into the target directory..."
	cp -f "${ACME_ROOT_CA_ANCHOR}" "${SSL_DIR}/ca-root.pem"
	say "\t✅ Done!"

	################################################################################
	#
	# Trust the certificates we're told to trust
	#
	################################################################################
	doing "Deploying the common trusted certificates from [${SSL_TRUSTS_DIR}]"
	is_dir_writable "${SSL_TRUSTS_DIR}" || mkdir -p "${SSL_TRUSTS_DIR}"
	SSL_TRUSTS_DIR="$(readlink -f "${SSL_TRUSTS_DIR}")"

	COUNT=0
	while read cert ; do
		CERT="${cert##*/}"
		if [ ! -f "${cert}" ] ; then
			say "\tWARNING: The certificate [${CERT}] is not a regular file, skipping"
			continue
		fi

		case "${CERT,,}" in
			# If the data is an actual certificate, copy it verbatim
			*.pem | *.crt )
				say "\tDeploying certificate [${CERT}]..."
				install_chain "${OS_SSL_ANCHORS}/${CERT%.*}" "${OS_SSL_SUFFIX}" < "${cert}"
				;;

			# If the data is a URL, then try to pull it down and put the resulting file into
			# the correct location using ${CERT} as the name
			*.url )
				STR="$(<"${cert}")"
				URL="$(expand_vars "${STR}" 2>&1)" || { warn "Failed to expand the environment variables contained in [${STR}] (rc=${?}): ${URL}" ; continue ; }
				is_valid_url "${URL}" || fail "\tThe certificate [${CERT}] is invalid - the URL syntax is invalid: [${URL}]"
				say "\tDownloading the certificate [${CERT}] from [${URL}]..."
				download_chain "${OS_SSL_ANCHORS}/${CERT%.*}" "${URL}" "${OS_SSL_SUFFIX}" || fail "\tFailed to download the certificate [${CERT}] from the URL [${URL}]"
				;;

			*.ssl )
				STR="$(<"${cert}")"
				SERVER="$(expand_vars "${STR}" 2>&1)" || { warn "Failed to expand the environment variables contained in [${STR}] (rc=${?}): ${SERVER}" ; continue ; }
				[[ "${SERVER}" =~ ^(([^@]+)@)?(([^:]+):([0-9]+))(/(.*))?$ ]] || fail "\tThe certificate [${CERT}] is invalid - the server string [${SERVER}] did not match the required pattern ([serverName@]hostNameOrIP:port[/tls-protocol])"
				SERVER_NAME="${BASH_REMATCH[2]}"
				HOST_NAME="${BASH_REMATCH[4]}"
				PORT="${BASH_REMATCH[5]}"
				TLS_PROTOCOL_STR="${BASH_REMATCH[6]}"
				TLS_PROTOCOL="${BASH_REMATCH[7],,}"
				if [ -n "${SERVER_NAME}" ] ; then
					is_valid_hostname "${SERVER_NAME}" || fail "\tInvalid server name [${SERVER_NAME}] in spec [${SERVER}] from [${CERT}]"
				fi
				is_valid_hostname "${HOST_NAME}" || fail "\tInvalid host name [${HOST_NAME}] in spec: [${SERVER}] from [${CERT}]"
				is_valid_port "${PORT}" || fail "\tInvalid port number [${PORT}] in spec: [${SERVER}] from [${CERT}]"
				DESCRIPTION="SSL server [${SERVER}]"
				if [ -n "${TLS_PROTOCOL_STR}" ] ; then
					case "${TLS_PROTOCOL}" in
						ftp | imap | irc | ldap | lmtp | mysql | nntp | pop3 | postgres | sieve | smtp | xmpp | xmpp-server ) ;;
						* ) fail "\tUnsupported TLS protocol [${TLS_PROTOCOL}]" ;;
					esac
					DESCRIPTION="TLS server [${SERVER}] (${TLS_PROTOCOL})"
				fi
				say "\tDownloading the certificate [${CERT}] from the ${DESCRIPTION} ..."
				download_from_port "${HOST_NAME}" "${SERVER_NAME}" "${PORT}" "${TLS_PROTOCOL}" "${OS_SSL_ANCHORS}" "${OS_SSL_SUFFIX}" || fail "\tFailed to download the certificate from the ${DESCRIPTION} as requested by [${CERT}]"
				;;

			* )
				say "\tWARNING: Don't know how to handle certificate [${CERT}], skipping"
				continue
				;;
		esac

		(( ++COUNT ))
	done < <(find "${SSL_TRUSTS_DIR}" -mindepth 1 -maxdepth 1 -name "ssl-trust-*.*" | sort)
	if [ ${COUNT} -eq 0 ] ; then
		say "\t✅ No certificates to deploy."
	else
		say "\t✅ Deployed ${COUNT} certificates!"
	fi

	# This array will contain the list of (absolute) paths for all
	# files whose ownership and permissions will be set to the most
	# restrictive of all: only readable by the owner
	SECURE_FILES=()

	# This helps us do cleanup on exit
	GARBAGE=()

	################################################################################
	#
	# Generate the key's password file
	#
	################################################################################
	if [ -v ACME_KEYSTORE_PASSWORD_FILE ] ; then
		[ -n "${ACME_KEYSTORE_PASSWORD_FILE}" ] || fail "The variable ACME_KEYSTORE_PASSWORD_FILE may not be empty"
		[ -s "${ACME_KEYSTORE_PASSWORD_FILE}" ] || fail "The password file [${ACME_KEYSTORE_PASSWORD_FILE}] may not be empty"
	else
		# We weren't given a password file to use, so use the default value
		ACME_KEYSTORE_PASSWORD_FILE="${SSL_DIR}/.password"

		# Allow the use of ACME_KEYSTORE_PASSWORD to set the password. This isn't
		# particularly secure, but it may be required in some instances where the
		# pod needs to know the password beforehand (i.e. b/c Helm needs to know it)
		if [ -v ACME_KEYSTORE_PASSWORD ] ; then
			[ -n "${ACME_KEYSTORE_PASSWORD}" ] || fail "The variable ACME_KEYSTORE_PASSWORD may not be empty"
			echo -n "${ACME_KEYSTORE_PASSWORD}" > "${ACME_KEYSTORE_PASSWORD_FILE}" || fail "Failed to render the password file at [${ACME_KEYSTORE_PASSWORD_FILE}] with the password given in ACME_KEYSTORE_PASSWORD"
		else
			# We weren't given a password, so just render a random one
			render_password > "${ACME_KEYSTORE_PASSWORD_FILE}" || fail "Failed to render a new password into [${ACME_KEYSTORE_PASSWORD_FILE}]"
		fi
	fi

	export ACME_KEYSTORE_PASSWORD="$(<"${ACME_KEYSTORE_PASSWORD_FILE}")"
	SECURE_FILES+=("${ACME_KEYSTORE_PASSWORD_FILE}")

	################################################################################
	#
	# If we're doing the Java thing, then set up all the Java stuff
	#
	################################################################################
	if as_boolean "${KEYTOOL}" ; then

		set_or_default JAVA_SSL_KEYSTORE_TYPE "BCFKS"
		set_or_default JAVA_SSL_KEYSTORE_PROVIDER "org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider"
		set_or_default JAVA_SSL_KEYSTORE_PROVIDER_PATH "${FIPS_DIR:-}"
		set_or_default JAVA_SSL_KEYSTORE_PROVIDER_ARGS

		# The path must be a directory, not a file
		if is_dir_readable "${JAVA_SSL_KEYSTORE_PROVIDER_PATH}" ; then
			JARS=""
			while read JAR ; do
				is_file_readable "${JAR}" && JARS+="${JARS:+:}${JAR}" && continue
				warn "The Keystore provider file [${JAR}] is not readable!"
			done < <(find "${JAVA_SSL_KEYSTORE_PROVIDER_PATH}" -mindepth 1 -maxdepth 1 -type f \( -iname '*.jar' -or -iname '*.zip' \) | sort -u)
			[ -n "${JARS}" ] && JAVA_SSL_KEYSTORE_PROVIDER_PATH="${JARS}" || warn "No SSL providers found at ${JAVA_SSL_KEYSTORE_PROVIDER_PATH@Q}"
		elif [ -n "${JAVA_SSL_KEYSTORE_PROVIDER_PATH}" ] ; then
			fail "The value for JAVA_SSL_KEYSTORE_PROVIDER_PATH must be a directory, which ${JAVA_SSL_KEYSTORE_PROVIDER_PATH@Q} is not!"
		fi

		#
		# Define all the Java-related variables
		#
		export JAVA_KEYSTORE_TYPE="${JAVA_SSL_KEYSTORE_TYPE}"
		export JAVA_KEYSTORE="${SSL_DIR}/keystore.${JAVA_KEYSTORE_TYPE,,}"
		export JAVA_KEYSTORE_PASSWORD="${ACME_KEYSTORE_PASSWORD}"
		export JAVA_KEYSTORE_PASSWORD_FILE="${ACME_KEYSTORE_PASSWORD_FILE}"
		export JAVA_KEYSTORE_PROVIDER="${JAVA_SSL_KEYSTORE_PROVIDER}"
		export JAVA_KEYSTORE_PROVIDER_PATH="${JAVA_SSL_KEYSTORE_PROVIDER_PATH}"
		export JAVA_KEYSTORE_PROVIDER_ARGS="${JAVA_SSL_KEYSTORE_PROVIDER_ARGS}"

		export JAVA_TRUSTSTORE_TYPE="${JAVA_KEYSTORE_TYPE}"
		export JAVA_TRUSTSTORE="${JAVA_KEYSTORE}"
		export JAVA_TRUSTSTORE_PASSWORD="${JAVA_KEYSTORE_PASSWORD}"
		export JAVA_TRUSTSTORE_PASSWORD_FILE="${JAVA_KEYSTORE_PASSWORD_FILE}"
		export JAVA_TRUSTSTORE_PROVIDER="${JAVA_KEYSTORE_PROVIDER}"
		export JAVA_TRUSTSTORE_PROVIDER_PATH="${JAVA_KEYSTORE_PROVIDER_PATH}"
		export JAVA_TRUSTSTORE_PROVIDER_ARGS="${JAVA_KEYSTORE_PROVIDER_ARGS}"

		export JAVA_GLOBAL_TRUSTSTORE="${OS_SSL_CACERTS}"
		export JAVA_GLOBAL_TRUSTSTORE_TYPE="JKS"
		export JAVA_GLOBAL_TRUSTSTORE_PASSWORD="changeit"

		JAVAX_NET_SSL_OPTS=(
			-Djavax.net.ssl.keyStore='${JAVA_KEYSTORE}'
			-Djavax.net.ssl.keyStorePasswordFile='${JAVA_KEYSTORE_PASSWORD_FILE}'
			-Djavax.net.ssl.keyStorePassword='${JAVA_KEYSTORE_PASSWORD}'
			-Djavax.net.ssl.keyStoreType='${JAVA_KEYSTORE_TYPE}'

			-Djavax.net.ssl.trustStore='${JAVA_TRUSTSTORE}'
			-Djavax.net.ssl.trustStorePasswordFile='${JAVA_TRUSTSTORE_PASSWORD_FILE}'
			-Djavax.net.ssl.trustStorePassword='${JAVA_TRUSTSTORE_PASSWORD}'
			-Djavax.net.ssl.trustStoreType='${JAVA_TRUSTSTORE_TYPE}'

			-Dssl.KeyManagerFactory.algorithm="PKIX"
			-Dssl.TrustManagerFactory.algorithm="PKIX"
		)

		export KEYTOOL_PROVIDER_FLAGS=()
		if [ -n "${JAVA_KEYSTORE_PROVIDER}" ] ; then
			KEYTOOL_PROVIDER_FLAGS+=(-providerclass "${JAVA_KEYSTORE_PROVIDER}")
			[ -n "${JAVA_KEYSTORE_PROVIDER_ARGS}" ] && KEYTOOL_PROVIDER_FLAGS+=(-providerarg "${JAVA_KEYSTORE_PROVIDER_ARGS}")
			[ -n "${JAVA_KEYSTORE_PROVIDER_PATH}" ] && KEYTOOL_PROVIDER_FLAGS+=(-providerpath "${JAVA_KEYSTORE_PROVIDER_PATH}")
		fi
	fi

	################################################################################
	#
	# Generate our new certificates
	#
	################################################################################
	set_or_default ACME_PASSWORD_FILE "/.acme.password"
	if [ -f "${ACME_PASSWORD_FILE}" ] ; then
		################################################################################
		#
		# Compute all the values to be added to the certificate's SAN
		#
		################################################################################
		FQDN="$(hostname -f)"
		IFS="." read POD SERVICE NAMESPACE SVC CLUSTER_DOMAIN <<< "${FQDN}"

		set_or_default SSL_EXTRA_SAN
		set_as_boolean SSL_EXTRA_SAN_STRICT
		set_or_default SSL_SERVICE_EXTRA_NAMES

		VARIATIONS=( "${NAMESPACE}" "${SVC}" "${CLUSTER_DOMAIN}" )

		SAN=( ${FQDN} $(list_hostname_variations "${POD}" "${SERVICE}" "${VARIATIONS[@]}") )

		[ -n "${SERVICE}" ] && \
			SAN+=( $(list_hostname_variations "${SERVICE}" "${VARIATIONS[@]}") )

		# ACME_SERVICE_NAME is the "consumable" service, while
		# SERVICE is the (possibly headless) default service
		# associated to a pod. They *may* be the same but
		# aren't required to be. Thus, we check to see if they're
		# the same, to avoid adding duplicate values
		set_or_default ACME_SERVICE_NAME "${SERVICE}"
		[ "${ACME_SERVICE_NAME}" != "${SERVICE}" ] && \
			SAN+=( $(list_hostname_variations "${ACME_SERVICE_NAME}" "${VARIATIONS[@]}") )

		# These are extra service names through which this
		# same pod may be reached
		#
		# The string may have multiple basenames (no dots!),
		# and be separated by commas, spaces, or colons
		while read EXTRA_NAME ; do
			is_valid_hostname_part "${EXTRA_NAME}" || continue
			SAN+=( $(list_hostname_variations "${EXTRA_NAME}" "${VARIATIONS[@]}") )
		done < <(split_hostnames "${SSL_SERVICE_EXTRA_NAMES}")

		[ -v POD_IP ] && \
			POD_IP="$(validate_ip "${POD_IP}")" && [ "${POD_IP}" != "127.0.01" ] && SAN+=("${POD_IP}")

		# The least specific values
		SAN+=(
			"${POD}"
			"localhost.localdomain"
			"localhost"
		)

		# These two are added to support developer machines, but they only get enabled
		# when using our developer-centric K8s deployment
		#
		set_or_default LOCAL_DEV_HOSTNAME "k8s.cluster.prv"
		if is_valid_hostname "${LOCAL_DEV_HOSTNAME}" ; then
			# This should be an instant resolve for our developer machines
			LOCAL_DEV_IPV4="$(dig +short +timeout=1 +retry=0 "${LOCAL_DEV_HOSTNAME}" 2>&1)"
			if is_valid_ipv4 "${LOCAL_DEV_IPV4}" ; then
				warn "Adding the local development SAN entries: ${LOCAL_DEV_HOSTNAME}/${LOCAL_DEV_IPV4}"
				SAN+=(
					"${LOCAL_DEV_IPV4}"
					"${LOCAL_DEV_HOSTNAME}"
				)
			fi
		fi

		# Add the extra SAN names, if provided. The list can be separated by spaces, commas, or colons
		while read S ; do
			if is_valid_ipv4 "${S}" || is_valid_hostname "${S}" ; then
				SAN+=("${S}")
			else
				# If we're strict, we explode ... we don't warn
				as_boolean "${SSL_EXTRA_SAN_STRICT}" && CMD="fail" || CMD="warn"
				"${CMD}" "The value [${S}] from SSL_EXTRA_SAN is neither a valid IP nor a valid hostname"
			fi
		done < <(split_hostnames "${SSL_EXTRA_SAN}")

		ensure_dir "${SSL_DIR}"

		################################################################################
		#
		# Render the certificate (different if Java is used vs. not)
		#
		################################################################################
		if as_boolean "${KEYTOOL}" ; then
			doing "Rendering a ${JAVA_KEYSTORE_TYPE} Keystore with the new certificate & key..."

			export JAVA_KEY_ALIAS="acme"
			export JAVA_KEY_PASSWORD="${JAVA_KEYSTORE_PASSWORD}"
			export JAVA_KEY_PASSWORD_FILE="${JAVA_KEYSTORE_PASSWORD_FILE}"

			JAVAX_NET_SSL_OPTS+=(
				-Djavax.net.ssl.keyAlias='${JAVA_KEY_ALIAS}'
				-Djavax.net.ssl.keyPasswordFile='${JAVA_KEY_PASSWORD_FILE}'
				-Djavax.net.ssl.keyPassword='${JAVA_KEY_PASSWORD}'
			)

			KT_SAN=""
			[ "${#SAN[@]}" -gt 0 ] && doing "Rendering certificate for the following SANs:"
			while read S ; do
				say "\t${S}"
				is_valid_ipv4 "${S}" && TYPE="ip" || TYPE="dns"
				[ -n "${KT_SAN}" ] && KT_SAN+=","
				KT_SAN+="${TYPE}:${S}"
			done < <(echo "${SAN[@]}" | tr '[:space:]' '\n' | sed -e '/^\s*$/d' | sort -u)
			[ -n "${KT_SAN}" ] && KT_SAN=(-ext "san=${KT_SAN}") || KT_SAN=()

			# First, generate the certificate key
			doing "Generating the certificate key..."
			CMD=(
				keytool -genkey
					-alias "${JAVA_KEY_ALIAS}"
					-dname "CN=${FQDN}"
					-keyalg RSA
					-keypass "$(<"${JAVA_KEYSTORE_PASSWORD_FILE}")"
					-keysize 2048
					-keystore "${JAVA_KEYSTORE}"
					-storetype "${JAVA_KEYSTORE_TYPE}"
					-storepass "$(<"${JAVA_KEYSTORE_PASSWORD_FILE}")"
					-startdate "-90m"
					-validity 548
					"${KT_SAN[@]}"
					"${KEYTOOL_PROVIDER_FLAGS[@]}"
			)
			OUT="$("${CMD[@]}" 2>&1)" || fail "Failed to generate the ${JAVA_KEYSTORE_TYPE} keystore (rc=${?}): ${OUT}"
			ok "The key is ready!"

			# Generate the CSR
			doing "Generating the certificate signing request..."
			CSR="$(mktemp --tmpdir="${SSL_DIR}" .csr.XXXXXXXX)" || fail "Failed to create a temporary CSR file"
			GARBAGE+=( "${CSR}" )
			CMD=(
				keytool -certreq
					-alias "${JAVA_KEY_ALIAS}"
					-file "${CSR}"
					-keystore "${JAVA_KEYSTORE}"
					-keypass "$(<"${JAVA_KEYSTORE_PASSWORD_FILE}")"
					-storetype "${JAVA_KEYSTORE_TYPE}"
					-storepass "$(<"${JAVA_KEYSTORE_PASSWORD_FILE}")"
					"${KT_SAN[@]}"
					"${KEYTOOL_PROVIDER_FLAGS[@]}"
			)
			OUT="$("${CMD[@]}" 2>&1)" || fail "Failed to generate the CSR (rc=${?}): ${OUT}"
			ok "The request is ready!"

			# Get the CSR signed
			CERT="${SSL_DIR}/cert.pem"
			GARBAGE+=( "${CERT}" )
			TMP_CERT="$(mktemp --tmpdir="${SSL_DIR}" ".temp-cert-XXXXXXXX.pem")"
			GARBAGE+=( "${TMP_CERT}" )
			doing "Submitting the certificate signing request..."
			step ca sign "${CSR}" "${TMP_CERT}" \
				--force \
				--not-before="-1h30m" \
				--provisioner-password-file "${ACME_PASSWORD_FILE}" \
				--password-file="${ACME_KEYSTORE_PASSWORD_FILE}" || fail "Failed to get the certificate signature"
			ok "The certificate was signed!"

			# Extract the certificate and any intermediates chain (don't import, will happen automatically later)
			split_signed_cert "${TMP_CERT}" "${CERT}" "${SSL_DIR}/ca-chain.pem" "${SSL_DIR}/ca-root.pem" "${SSL_DIR}/ca-int.pem"
			is_file_readable "${SSL_DIR}/ca-chain.pem" && install_chain "${OS_SSL_ANCHORS}/ca-int" "${OS_SSL_SUFFIX}" < "${SSL_DIR}/ca-int.pem"

			# We import the signers as well
			doing "Importing the signed certificate into the keystore..."
			CMD=(
				keytool -import
					-alias "${JAVA_KEY_ALIAS}"
					-file "${TMP_CERT}"
					-keystore "${JAVA_KEYSTORE}"
					-noprompt
					-storetype "${JAVA_KEYSTORE_TYPE}"
					-storepass "$(<"${JAVA_KEYSTORE_PASSWORD_FILE}")"
					"${KEYTOOL_PROVIDER_FLAGS[@]}"
			)
			OUT="$("${CMD[@]}" 2>&1)" || fail "Failed to import the signed certificate into the keystore (rc=${?}): ${OUT}"
			say "\t✅ The keystore is ready!"
		else
			########################################
			# No Java, use OpenSSL only
			########################################
			# Make sure our SAN list is unique, and
			# sorted, and pre-pend the --san argument
			SAN_ARG=()
			[ "${#SAN[@]}" -gt 0 ] && doing "Rendering certificate for the following SANs:"
			while read S ; do
				say "\t${S}"
				SAN_ARG+=(--san "${S}")
			done < <(echo "${SAN[@]}" | tr '[:space:]' '\n' | sed -e '/^\s*$/d' | sort -u)

			# Note: the not-before is "back in time" to accommodate for clock skew. We've
			# observed that when there's a bit of clock skew, certificate issuance goes
			# kind of wonky b/c the cert will be OK, but it will not be accepted by the
			# consuming processes until the not-before time has past. By using a back-in-time
			# approach we ensure that the certificate will always be "born ready"
			CERT="${SSL_DIR}/cert.pem"
			TMP_CERT="$(mktemp --tmpdir="${SSL_DIR}" ".temp-cert-XXXXXXXX.pem")"
			GARBAGE+=( "${TMP_CERT}" )
			doing "Rendering a new certificate for this pod's use"
			step ca certificate \
				"${FQDN}" "${TMP_CERT}" "${SSL_DIR}/cert.key" \
				"${SAN_ARG[@]}" \
				--force \
				--not-before="-1h30m" \
				--size 2048 \
				--kty RSA \
				--provisioner-password-file "${ACME_PASSWORD_FILE}" \
				--password-file="${ACME_KEYSTORE_PASSWORD_FILE}"

			# Extract the certificate and any intermediates chain (don't import, will happen automatically later)
			split_signed_cert "${TMP_CERT}" "${CERT}" "${SSL_DIR}/ca-chain.pem" "${SSL_DIR}/ca-root.pem" "${SSL_DIR}/ca-int.pem"
			is_file_readable "${SSL_DIR}/ca-chain.pem" && install_chain "${OS_SSL_ANCHORS}/ca-int" "${OS_SSL_SUFFIX}" < "${SSL_DIR}/ca-int.pem"

			set_as_boolean SSL_DH_APPEND "false"
			if as_boolean "${SSL_DH_APPEND}" ; then
				set_or_default SSL_DH_SIZE "1024"
				doing "Rendering the Diffie-Hellman parameters..."
				OUT="$(openssl dhparam -outform pem -out "${SSL_DIR}/dh.pem" "${SSL_DH_SIZE}" 2>&1)"  || fail "Failed to generate the DH parameters (rc=${?}): ${OUT}"
				doing "Appending Diffie-Hellman parameters to the certificate"
				( echo "" ; cat "${SSL_DIR}/dh.pem" ) >> "${CERT}" || fail "Failed to append the DH parameters to the certifiate"
				say "\tDH parameters appended!"
			fi
			SECURE_FILES+=("${SSL_DIR}/cert.key")

			doing "Creating a AES (PKCS8) encrypted version of the key..."
			openssl pkcs8 -topk8 \
				-nocrypt \
				-in "${SSL_DIR}/cert.key" \
				-out "${SSL_DIR}/cert.key.aes" \
				-v2 aes-256-cbc \
				-passout env:ACME_KEYSTORE_PASSWORD \
				&& say "\t✅ AES-256 (PKCS8) Encrypted key ready!" \
				|| warn "Failed to create the AES-256 (PKCS8) Encrypted certificate key"

			doing "Rendering the certificate files for HAProxy..."
			cat \
				"${CERT}" \
				"${SSL_DIR}/ca-chain.pem" \
				"${SSL_DIR}/cert.key" \
				> "${SSL_DIR}/haproxy-cert.pem"
			SECURE_FILES+=("${SSL_DIR}/haproxy-cert.pem")
			say "\t✅ Done!"
		fi

		doing "Protecting the generated data..."

		say "\t✅ Done!"
	else
		err "Couldn't find the provisioner password file at [${ACME_PASSWORD_FILE}], did not generate any new certificates or keystores"
	fi

	doing "Updating the trusted certificates..."
	chown -R root:root "${OS_SSL_ANCHORS}"
	chmod -R u=rwX,go=rX "${OS_SSL_ANCHORS}"
	OUT="$(execute "${OS_SSL_UPDATE_CMD[@]}" 2>&1)" || fail "Failed to update the CA trusts (rc=${?}): ${OUT}"
	say "\t✅ CA trusts updated system-wide!"

	#
	# This little block HAS to happen after the OS's anchors are updated
	# using the O/S tool, to ensure that all the required certificates
	# get copied correctly, and we don't miss anything
	#
	# Also we only do this if we built a keystore ... if we didn't build one,
	# we don't really care
	#
	if as_boolean "${KEYTOOL}" ; then
		doing "Adding the global trusts to the ${JAVA_KEYSTORE_TYPE} keystore!"
		CMD=(
			keytool -importkeystore
				-destkeystore "${JAVA_KEYSTORE}"
				-deststorepass "$(<"${JAVA_KEYSTORE_PASSWORD_FILE}")"
				-deststoretype "${JAVA_KEYSTORE_TYPE}"
				-noprompt
				-srckeystore "${JAVA_GLOBAL_TRUSTSTORE}"
				-srcstorepass "${JAVA_GLOBAL_TRUSTSTORE_PASSWORD}"
				-srcstoretype "${JAVA_GLOBAL_TRUSTSTORE_TYPE}"
				"${KEYTOOL_PROVIDER_FLAGS[@]}"
		)
		OUT="$("${CMD[@]}" 2>&1)" \
			&& say "\t✅ Global trusts added!" \
			|| err "Could not append the global trusts from [${JAVA_GLOBAL_TRUSTSTORE}] (rc=${?}): ${OUT}"

		#
		# Add the Java variables to the environment file
		# in preparation for the final output
		#
		SSL_ENV_FILE_VARS+=(
			JAVA_KEYSTORE
			JAVA_KEYSTORE_PASSWORD_FILE
			JAVA_KEYSTORE_PASSWORD
			JAVA_KEYSTORE_TYPE
			JAVA_KEYSTORE_PROVIDER
			JAVA_KEYSTORE_PROVIDER_PATH
			JAVA_KEYSTORE_PROVIDER_ARGS

			JAVA_TRUSTSTORE
			JAVA_TRUSTSTORE_PASSWORD_FILE
			JAVA_TRUSTSTORE_PASSWORD
			JAVA_TRUSTSTORE_TYPE
			JAVA_TRUSTSTORE_PROVIDER
			JAVA_TRUSTSTORE_PROVIDER_PATH
			JAVA_TRUSTSTORE_PROVIDER_ARGS

			JAVA_GLOBAL_TRUSTSTORE
			JAVA_GLOBAL_TRUSTSTORE_TYPE
			JAVA_GLOBAL_TRUSTSTORE_PASSWORD
		)

		if [ -v JAVA_KEY_ALIAS ] ; then
			SSL_ENV_FILE_VARS+=(
				JAVA_KEY_ALIAS
				JAVA_KEY_PASSWORD_FILE
				JAVA_KEY_PASSWORD
			)
		fi

		# Add these two last, in case there's no reason to add them
		[ -n "${JAVA_KEYSTORE_PROVIDER}" ] && JAVAX_NET_SSL_OPTS+=( -Djavax.net.ssl.keyStoreProvider='${JAVA_KEYSTORE_PROVIDER}' )
		[ -n "${JAVA_TRUSTSTORE_PROVIDER}" ] && JAVAX_NET_SSL_OPTS+=( -Djavax.net.ssl.trustStoreProvider='${JAVA_TRUSTSTORE_PROVIDER}' )

		# This one goes last b/c it'll be the biggest and baddest, so the file is easier to read
		SSL_ENV_FILE_VARS+=( JAVAX_NET_SSL_OPTIONS )

		#
		# Render the final JVM options consuming all the above variables
		#
		export JAVAX_NET_SSL_OPTIONS="$(echo -n "${JAVAX_NET_SSL_OPTS[@]}" | envsubst)"
	fi

	# By default, owned by root but readable by everyone
	chown -R "root:${ACM_GROUP}" "${SSL_DIR}"
	chmod -R ug=rX,o= "${SSL_DIR}"

	# Secure the most sensitive files so they're only readable
	# by the user who will be consuming them ... the other files
	# can easily be world-readable since they're all encrypted
	# one way or another, or are meant to be publicly-accessible
	if [ ${#SECURE_FILES[@]} -gt 0 ] ; then
		doing "Securing the private SSL files: [ ${SECURE_FILES[@]@Q} ]"
		[ -v SUDO_USER ] && KEY_OWNER="${SUDO_USER}" || KEY_OWNER="root"
		chown "${KEY_OWNER}:${ACM_GROUP}" "${SECURE_FILES[@]}"
		chmod u=r,go= "${SECURE_FILES[@]}"
	fi

	export RESULT_OK="true"
	as_boolean "${FIPS}" && FIPS_LABEL=" (FIPS is active)" || FIPS_LABEL=""
	ok "SSL ready! The environment can be configured by sourcing [${SSL_ENV_FILE}]${FIPS_LABEL}"
} 999<"${LOCK}"
