#!/bin/bash

set -euo pipefail
. /.functions

set_or_default SSL_DIR "/.ssl"

require_exe openssl sha256sum

wait_ssl

test-certificate "${@}" || exit ${?}

# Is the root certificate in the system trusts?
SSL_DIRECTORIES="$(find-ssl-dirs)" || fail "Failed to compute the local SSL configuration"
source <(echo -n "${SSL_DIRECTORIES}") || fail "Failed to apply the local SSL configuration"

HASH="$(openssl x509 -noout -hash -in "${SSL_CA_ROOT}" 2>&1)" || fail "Failed to compute the hash for the root certificate [${SSL_CA_ROOT}] (rc=${?}): ${HASH}"
HASH_FILE="/etc/ssl/certs/${HASH}.0"
is_file_readable "${HASH_FILE}" || fail "The root certificate isn't in the system's trusts!"

read SUM REST < <(sha256sum "${SSL_CA_ROOT}")
echo "${SUM} ${HASH_FILE}" | sha256sum --check --status || fail "The root certificate [${SSL_CA_ROOT}] is not the same as the trusted certificate in the system's store at [${HASH_FILE}]"

ok "SSL validation complete!"
exit 0
