#!/bin/bash

set -euo pipefail
. /.functions

set_or_default FIXES_DIR "/fixes"

[ ${#} -gt 0 ] || set -- "${FIXES_DIR}"

for DIR in "${@}" ; do
	require_dir_readwrite "${DIR}"

	doing "Applying fixes from [${DIR}] ..."

	COUNT=0
	while read FIX ; do
		doing "Applying ${FIX} ..."
		"${FIX}" && (( ++COUNT ))
		rm -f "${FIX}" &>/dev/null || true
	done < <(find "${DIR}" -mindepth 1 -maxdepth 1 -type f)

	rmdir "${DIR}" || warn "Failed to remove the fixes directory at [${DIR}]"

	ok "${COUNT} fixes applied from [${DIR}]!"
done
