apiVersion: v1
kind: Pod
metadata:
  name: arkcase-base
spec:
  containers:
    - name: base
      image: arkcase/base:latest
      imagePullPolicy: Always
      command: [ "sleep", "infinity" ]
  imagePullSecrets:
    - name: aws-arkcase-pull
