apiVersion: v1
kind: Pod
metadata:
  name: base
spec:
  containers:
    - name: base
      image: 345280441424.dkr.ecr.ap-south-1.amazonaws.com/ark_base:latest
      imagePullPolicy: Always
      command: [ "sleep", "infinity" ]
  imagePullSecrets:
    - name: aws-arkcase-pull
