#!/bin/bash

set -euo pipefail
. /.functions

# First off, set the termination flag
set_or_default LOOP_TERMINATION_FILE "/.terminate"

RC=0
touch "${LOOP_TERMINATION_FILE}" || RC=${?}

# If the command is set to "fail", then execution will stop there and
# the final "execute" invocation will not be reached
CMD="warn"
[ ${#} -gt 0 ] && CMD="fail"
"${CMD}" "Unable to set the termination marker at [${LOOP_TERMINATION_FILE}]"

# Now, run whatever termination command was requested
execute "${@}"
